apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: {{ include "task-api.fullname" . }}-healthcheck
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    config:
      type: HTTP
      httpHealthCheck:
        requestPath: /health
        port: {{ .Values.service.port }}
  targetRef:
    group: ""
    kind: Service
    name: {{ include "task-api.fullname" . }}