apiVersion: v1
kind: Secret
metadata:
  name: {{ include "task-api.fullname" . }}-db-secret
  labels:
    {{- include "task-api.labels" . | nindent 4 }}
type: Opaque
data:
  database-url: {{ .Values.database.url | b64enc }}